import type { Metadata } from 'next';
import '../../globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import clsx from 'clsx';
import NextTopLoader from 'nextjs-toploader';
import { ModalProvider } from '../../_contexts/modal-provider';
import { Toaster } from 'react-hot-toast';
import { getLangDir } from 'rtl-detect';
import GuestNavbar from '@app/_components/navbars/guest-navbar';
import Footer from '@app/_components/navbars/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  const locale = await getLocale();
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body
        className={clsx(
          'overflow-x-hidden',
          'text-textDark',
          'relative pt-[calc(var(--guestNavHeight))] bg-guestMainColor bg-fixed bg-cover bg-[url("/images/patterns/guest.png")]',
        )}>
        <div className="w-[100vw] h-[100%] bg-guestMainColor mix-blend-multiply absolute top-0 left-0" />
        <NextTopLoader />
        <Toaster position="top-center" reverseOrder={false} />

        <NextIntlClientProvider messages={messages}>
          <GuestNavbar />
          <ModalProvider>
            <main className="relative z-50">
              {children}
              <Footer />
            </main>
          </ModalProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

