import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '16px',
      },
    },
    extend: {
      screens: {
        xs: '400px', // Custom breakpoint for 400px
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in-out forwards',
        'fade-out': 'fade-out 0.3s ease-in-out forwards',
      },

      colors: {
        blue1: '#132863',
        blue2: '#021C63',
        blue3: '#3C57A4',
        gold1: '#CDAD8F',
        gold2: '#FAE1CB',
        textGray: '#929292',
        textGray2: '#848484',
        myColor: 'var(--myColor)',

        guestMainColor: 'var(--guestMainColor)',
        guestSecondary1: 'var(--guestSecondary1)',
        guestSecondary2: 'var(--guestSecondary2)',
        guestSecondary3: 'var(--guestSecondary3)',

        textLight: 'var(--textLight)',
        textDark: 'var(--textDark)',
        iconLight: 'var(--iconLight)',
        iconDark: 'var(--iconDark)',
        mainColor1: 'var(--mainColor1)',
        mainColor2: 'var(--mainColor2)',
        mainColor3: 'var(--mainColor3)',
        mainColor1Opacity: 'var(--mainColor1Opacity)',
        mainColor2Opacity: 'var(--mainColor2Opacity)',
        secondaryColor1: 'var(--secondaryColor1)',
        secondaryColor2: 'var(--secondaryColor2)',
        mainColorPie: 'var(--mainColorPie)',
        mainColorBar: 'var(--mainColorBar)',
        dangerColor: 'var(--dangerColor)',
        placeHolderColor: 'var(--placeHolderColor)',
        errorColor: 'var(--errorColor)',
        cardColor: 'var(--cardColor)',
        tableText: 'var(--tableText)',
        secondText: 'var(--secondText)',
        tableBorder: 'var(--tableBorder)',
        storageContainer: 'var(--storageContainer)',
        whiteBackground: 'var(--whiteBackground)',
        lowColor: 'var(--lowColor)',
        highColor: 'var(--highColor)',
      },
      height: {
        horizontalNavHeight: 'var(--horizontalNavHeight)',
        guestNavHeight: 'var(--guestNavHeight)',
        sectionHeight: 'calc(100vh - 100px)',
      },
      width: {
        verticalNavWidth: 'var(--verticalNavWidth)',
        verticalNavSmallWidth: 'var(--verticalNavSmallWidth)',
      },
      boxShadow: {
        activityLog: '0 0 4.4px rgba(19, 40, 99, 0.7)',
        tableShadow: '0 0 8px 0 rgba(19, 40, 99, 0.5)',
      },
      borderRadius: {
        bigRounded: '40px',
        navsRadius: 'var(--navsRadius)',
      },
      backgroundImage: {
        goldLinear:
          'linear-gradient(to right, var(--secondaryColor1), var(--secondaryColor1), var(--secondaryColor2))',
        goldText:
          'linear-gradient(to right, var(--guestSecondary1), var(--guestSecondary2), var(--guestSecondary3))',
        'custom-linear': 'linear-gradient(to right, #132863, #021C63)',
        horizontalNavLinear:
          'linear-gradient(to right, var(--mainColor1), var(--mainColor2))',
        horizontalNavLinearRTL:
          'linear-gradient(to left, var(--mainColor1), var(--mainColor2))',
        mainDashboardLinear:
          'linear-gradient(to bottom, var(--mainColor1Opacity), var(--mainColor2Opacity))',
        buttonLinear:
          'linear-gradient(to right, var(--mainColor1), var(--mainColor2))',
        guestLinear: 'linear-gradient(to top, transparent, #FFFFFF55)',
      },
      fontSize: {
        '8px': 'var(--font-size-8)',
        '10px': 'var(--font-size-10)',
        '12px': 'var(--font-size-12)',
        '14px': 'var(--font-size-14)',
        '16px': 'var(--font-size-16)',
        '18px': 'var(--font-size-18)',
        '20px': 'var(--font-size-20)',
        '22px': 'var(--font-size-22)',
        '24px': 'var(--font-size-24)',
        '26px': 'var(--font-size-26)',
        '28px': 'var(--font-size-28)',
        '30px': 'var(--font-size-30)',
        '32px': 'var(--font-size-32)',
        '36px': 'var(--font-size-36)',
        '40px': 'var(--font-size-40)',
        '42px': 'var(--font-size-42)',
        '48px': 'var(--font-size-48)',
        '56px': 'var(--font-size-56)',
        '64px': 'var(--font-size-64)',
        '72px': 'var(--font-size-72)',
        '80px': 'var(--font-size-80)',
        '96px': 'var(--font-size-96)',
        '108px': 'var(--font-size-108)',
        '120px': 'var(--font-size-120)',
        '128px': 'var(--font-size-128)',
      },
      spacing: {
        iconSpacing: '16px',
        navsBodySpacing: 'var(--navsBodySpacing)',
        searchBarTop: 'var(--searchBarTop)',
        activitySpace: 'var(--activitySpace)',
        guestNavSpacing: 'var(--guestNavHeight)',
        sectionPadding: 'var(--sectionPadding)',
        sectionGap: 'var(--sectionGap)',

        '4px': 'var(--space-4)',
        '8px': 'var(--space-8)',
        '10px': 'var(--space-10)',
        '12px': 'var(--space-12)',
        '14px': 'var(--space-14)',
        '16px': 'var(--space-16)',
        '18px': 'var(--space-18)',
        '20px': 'var(--space-20)',
        '22px': 'var(--space-22)',
        '24px': 'var(--space-24)',
        '26px': 'var(--space-26)',
        '28px': 'var(--space-28)',
        '30px': 'var(--space-30)',
        '32px': 'var(--space-32)',
        '36px': 'var(--space-36)',
        '40px': 'var(--space-40)',
        '42px': 'var(--space-42)',
        '48px': 'var(--space-48)',
        '56px': 'var(--space-56)',
        '64px': 'var(--space-64)',
        '72px': 'var(--space-72)',
        '80px': 'var(--space-80)',
        '96px': 'var(--space-96)',
        '108px': 'var(--space-108)',
        '120px': 'var(--space-120)',
        '128px': 'var(--space-128)',
        navHeight: 'var(--navHeight)',
      },
      gap: {
        '4px': 'var(--space-4)',
        '8px': 'var(--space-8)',
        '10px': 'var(--space-10)',
        '12px': 'var(--space-12)',
        '14px': 'var(--space-14)',
        '16px': 'var(--space-16)',
        '18px': 'var(--space-18)',
        '20px': 'var(--space-20)',
        '22px': 'var(--space-22)',
        '24px': 'var(--space-24)',
        '26px': 'var(--space-26)',
        '28px': 'var(--space-28)',
        '30px': 'var(--space-30)',
        '32px': 'var(--space-32)',
        '36px': 'var(--space-36)',
        '40px': 'var(--space-40)',
        '42px': 'var(--space-42)',
        '48px': 'var(--space-48)',
        '56px': 'var(--space-56)',
        '64px': 'var(--space-64)',
        '72px': 'var(--space-72)',
        '80px': 'var(--space-80)',
        '96px': 'var(--space-96)',
        '108px': 'var(--space-108)',
        '120px': 'var(--space-120)',
        '128px': 'var(--space-128)',
      },
      margin: {
        '4px': 'var(--space-4)',
        '8px': 'var(--space-8)',
        '10px': 'var(--space-10)',
        '12px': 'var(--space-12)',
        '14px': 'var(--space-14)',
        '16px': 'var(--space-16)',
        '18px': 'var(--space-18)',
        '20px': 'var(--space-20)',
        '22px': 'var(--space-22)',
        '24px': 'var(--space-24)',
        '26px': 'var(--space-26)',
        '28px': 'var(--space-28)',
        '30px': 'var(--space-30)',
        '32px': 'var(--space-32)',
        '36px': 'var(--space-36)',
        '40px': 'var(--space-40)',
        '42px': 'var(--space-42)',
        '48px': 'var(--space-48)',
        '56px': 'var(--space-56)',
        '64px': 'var(--space-64)',
        '72px': 'var(--space-72)',
        '80px': 'var(--space-80)',
        '96px': 'var(--space-96)',
        '108px': 'var(--space-108)',
        '120px': 'var(--space-120)',
        '128px': 'var(--space-128)',
      },
      padding: {
        '4px': 'var(--space-4)',
        '8px': 'var(--space-8)',
        '10px': 'var(--space-10)',
        '12px': 'var(--space-12)',
        '14px': 'var(--space-14)',
        '16px': 'var(--space-16)',
        '18px': 'var(--space-18)',
        '20px': 'var(--space-20)',
        '22px': 'var(--space-22)',
        '24px': 'var(--space-24)',
        '26px': 'var(--space-26)',
        '28px': 'var(--space-28)',
        '30px': 'var(--space-30)',
        '32px': 'var(--space-32)',
        '36px': 'var(--space-36)',
        '40px': 'var(--space-40)',
        '42px': 'var(--space-42)',
        '48px': 'var(--space-48)',
        '56px': 'var(--space-56)',
        '64px': 'var(--space-64)',
        '72px': 'var(--space-72)',
        '80px': 'var(--space-80)',
        '96px': 'var(--space-96)',
        '108px': 'var(--space-108)',
        '120px': 'var(--space-120)',
        '128px': 'var(--space-128)',
      },
      fontFamily: {
        content: ['Rubik'], // For content text
        head: ['Readex Pro'], // For headings
      },
    },
  },
  plugins: [],
} satisfies Config;

