import type { Metadata } from 'next';
import '../globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import VerticalNavbar from '../_components/navbars/vertical-navbar';
import HorizontalNavbar from '../_components/navbars/horizontal-navbar';
import clsx from 'clsx';
import NextTopLoader from 'nextjs-toploader';
import { getCookie } from 'cookies-next';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  // const allCookies = await cookies();

  // const isAuth = !!allCookies.get('token');
  // console.log(allCookies);

  const isAuth = true;

  return (
    <html lang="en">
      <body
        className={clsx(
          isAuth &&
            'pl-[calc(100px+32px)] lg:pl-[calc(213px+32px)] pt-[calc(104px+24px)] pr-[32px]',
          !isAuth && '',
        )}>
        <NextTopLoader />
        <NextIntlClientProvider messages={messages}>
          {isAuth && (
            <>
              <VerticalNavbar />
              <HorizontalNavbar />
            </>
          )}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

